### PR TITLE
feat: routing

### PR DESCRIPTION
**Pull request by prachi-sahu-codes**
Add: Pages routes #8
Add: Navbar component
Add: Primary Button

### CODE REVIEW

**Comment by atapas** [comment]
@prachi-sahu-codes Can you fix this?

image

**Comment by prachi-sahu-codes** [comment]
ok

**Comment by atapas** [comment]
@prachi-sahu-codes The header sill got a styling issue

image

**Comment by atapas** [comment]
Thanks for fixing it @prachi-sahu-codes 

Let's create a route explicitly for /conference

image

When we land to the app.. it lands into /conference

**Review by atapas — APPROVED** [review]

**Pull request merged**
