### PR TITLE
Conference API

### PR DESCRIPTION
**Pull request by prachi-sahu-codes**
Add: Finalized the Queries to get Conferences Data #2

### CODE REVIEW

**Comment by atapas** [comment]
@prachi-sahu-codes So if has all the queries except the filter by continent and country?

**Comment by prachi-sahu-codes** [comment]
Yes It has all the other queries.

**Comment by atapas** [comment]
> Yes It has all the other queries.

Alright, we will merge it but will not close the issue # 2 until the other query is done. You can create a new PR for it later when things are clear.

**Review by atapas — APPROVED** [review]
Looks Good to me

**Comment by prachi-sahu-codes** [comment]
Ok

**Pull request merged**
